### PR TITLE
Add option to allow fuzzy translations

### PR DESCRIPTION
**Pull request by jorrit**
I'd like to allow fuzzy translations in my application. It should be an easy change.

### CODE REVIEW

**Comment by AlexMost** [comment]
Wow! Thanks, seems like a nice to have feature!

**Comment by AlexMost** [comment]
this option is available in `babel-plugin-ttag@1.8.15` :tada:

**Comment by jorrit** [comment]
Thank you!

**Comment by jorrit** [comment]
Could you create a matching `ttag-cli` release?

**Pull request merged**
