### PR TITLE
Extract variables names to placeholders in .po and .pot files

### PR DESCRIPTION
**Pull request by oleksandr-kuzmenko**
I started implement https://github.com/c-3po-org/c-3po/issues/20
On the next step I'll implement `transform our translations object (json with translations) in form of Hello ${ username } to Hello ${ 0 } in the runtime` in `c-3po` lib.

/cc @AlexMost @MrOrz

### CODE REVIEW

**Comment by AlexMost** [comment]
One thing that we should keep in mind, that we already have translations in .po files with `${ 0 }` format. It would be great to have some migration script to the new format which will take old .po file, new .pot file and produce updated .po file with new format translations.

**Comment by MrOrz** [comment]
I thought gettext's `msgmerge`'s fuzzy matching already could handle the migration when we provide a .pot file with `${variable}` and a .po file with `${0}` to `msgmerge`. Is there anything I missed?

**Comment by oleksandr-kuzmenko** [comment]
@MrOrz you're right, but in a large project, it will be difficult for translator to confirm big amount of fuzzy translations

**Comment by MrOrz** [comment]
Tried it out in a production app. It correctly extracts and resolves variables in correct order for `ngettext` and `jt` as well. Great job @alxpy !

**Comment by oleksandr-kuzmenko** [comment]
@MrOrz sorry, I didn't notice your message. Thx=)

**Comment by AlexMost** [comment]
Great job! LGTM!

**Comment by AlexMost** [comment]
There is also one thing to notice, is that we should update docs accordingly to new changes. Maybe in separate PR.

**Pull request merged**
