### PR TITLE
Support comments before strings inside JSX

### PR DESCRIPTION
**Pull request by dhoko**
Hey :wave: 

We have an issue with ttag not able to export comments for a string if they are inside a JSX node. (via `ttag-cli extract`) 

cf 
```jsx
function render() {
  return (<>
      <h1>{
        // translator: this comment is for you AND IT WILL WORK
        c('valid-comment-1').t\`Title de ouf\`
      }</h1>
      <h2>{
        // this comment is NOT for you 
        c('invalid-comment').t\`Title de ouf pas ok?\`
      }</h2>
      <h2>{
        /* translator: OKAY this comment is for you */
        c('valid-comment-2').t\`Title de ouf ok?\`
      }</h2>
    <h3>{c('no-comment').t\`hahaha\`}</h3>
  </>)
}
``` 

Test added:
``` 
$ make test_extract_developer_comments_by_tag                                                                      
mocha --require @babel/register ./tests/functional/test_extract_developer_comments_by_tag.js                       
                                                                                                                   
                                                                                                                   
  Extract developer comments by tag                                                                                
    ✓ should extract comment comment (419ms)                                                                       
    ✓ should not extract comment                                                                                   
    ✓ should match with spaces after //                                                                            
    ✓ should extract comments inside JSX tags                                                                      
                                                                                                                   
                                                                                                                   
  4 passing (548ms)                                                                                                
                                                                                                                   ```

### CODE REVIEW

**Comment by nico3333fr** [comment]
Please please please, this one would save us a lot of time 🙏

**Comment by mmso** [comment]
@AlexMost would be great if you had time to take a look at this 🙏

**Comment by AlexMost** [comment]
Thanks for your contribution :+1: will check and release ASAP

**Comment by AlexMost** [comment]
:tada: Changes are available in versions:

* babel-plugin-ttag@1.8.4
* ttag-cli@1.10.3

**Pull request merged**
